### ISSUE TITLE
agentbar使用build.bat编译失败

### ISSUE THREAD

**Issue by happystar7788** [Baidu-ecom/CC#17]
使用agentbar目录下的build.bat文件编译出现以下Error错误，请各位高手帮忙看一下是什么问题？？

Microsoft (R) Cabinet Tool - Version 5.2.3668.0
Copyright (c) Microsoft Corporation. All rights reserved..

Creating new cabinet 'bin\CCAgentBar.cab' with compression 'MSZIP':
  -- adding bin\CCAgentBar.inf
FCIAddFile() failed: code 1 [Failure opening file to be stored in cabinet]

E:\学习\文档\呼叫中心\百度呼叫中心\CC-master\tools\agentbar>bin\signcode.exe -sp
c bin\CCAgentBar.spc -v bin\CCAgentBar.pvk bin\CCAgentBar.cab
Error: Unable to open a CSP provider with the correct private key
Error: Signing Failed.  Result = 80092006, (-2146885626)

**Comment by chenyuzhen** [comment]
相关编译依赖，如openssl编译失败
为了降低编译复杂性，现在已经将openssl放到了代码库
