### ISSUE TITLE
Agentbar 振铃问题

### ISSUE THREAD

**Issue by pzeyao** [Baidu-ecom/CC#22]
用控件内置SIP电话，来电振铃后如果座席未接电话，用户挂机，此时振铃不会停止

**Comment by chenyuzhen** [comment]
请提供下agentbar的相关日志，在c:\log\ 下

**Comment by pzeyao** [comment]
此问题似乎看日志没答案，日志里并未记录振铃开始和结束
似乎问题在代码Phonelib.cpp里 984行， 在函数
static void on_call_state_f(pjsua_call_id call_id, pjsip_event *e)
里
	if (call_info.state == PJSIP_INV_STATE_DISCONNECTED)
	{
		ring_stop(call_id);            // fix bug
		if(call_state_callback_f)

请看看这样修改是否正确，经测试问题解决

**Comment by kongdeyu** [comment]
按照描述场景进行了测试，没发现问题，能否提供下agentbar的相关日志，在c:\log\ 下

**Comment by billni** [comment]
@pzeyao   你的CC服务都部署成功了是吗？

**Comment by chenyuzhen** [comment]
测试没有问题，如果还有类似问题，请reopen或者直接新建issue，并提供相关日志信息
