### ISSUE TITLE
build libxml2 FAILED!

### ISSUE THREAD

**Issue by tim-john** [Baidu-ecom/CC#24]
# toolchain: 
* **OS**: Ubuntu 3.13.0-46-generic x86_64
* **GCC**: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

# make error message：
```bash
In file included from /usr/include/fcntl.h:205,
from nanohttp.c:49:
In function 'open',
inlined from 'xmlNanoHTTPSaveinternal_alias' at nanohttp.c:1588:12:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to 'open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
__open_missing_mode ();
^
make[1]: * [nanohttp.lo] Error 1
```

**Comment by chenyuzhen** [comment]
在 ubuntu平台上，针对open系统调用，如果指定了O_CREAT这个flag，则要求mode必须有。但是在centos没有这个强制要求
建议修改 这个是libxml2的nanohttp.c这个文件中的xmlNanoHTTPSave函数。

因为这个是第三方库代码，非呼叫中心平台的问题，建议自行修复

**Comment by tim-john** [comment]
谢谢回复！通过你的提示和 Googling，已经解决上述问题！谢谢！
需要为 **dep/libxml2/libxml2-2.6.30** 文件夹中的 **nanohttp.c** 的 `open` 函数调用增加第 3 个参数 0777。可以使用如下命令：
```
sed -i 's/fd = open(filename, O_CREAT | O_WRONLY);/fd = open(filename, O_CREAT | O_WRONLY, 0777);/' nanohttp.c
```
