### ISSUE TITLE
关于部署-合众

### ISSUE THREAD

**Issue by billni** [Baidu-ecom/CC#5]
1. 你们推荐的网关服务器有哪几种？
2.  坐席的电话机能否是模拟电话？
3. 单个IVR服务支持多少路？
4. 单个CTI服务支持多少坐席？
5. 是否需要掌握freeswitch，才能使用该系统？

**Comment by pzeyao** [comment]
发现个问题，用控件内置SIP电话，来电振铃后如果座席未接电话，用户挂机，此时振铃不会停止

**Comment by billni** [comment]
@chenyuzhen 
我们服务器操作系统。

[newcc@vm0166 CC-master]$ uname -a
Linux vm0166 2.6.18-308.el5 #1 SMP Fri Jan 27 17:17:51 EST 2012 x86_64 x86_64 x86_64 GNU/Linux
[newcc@vm0166 CC-master]$  lsb_release -a 
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.8 (Tikanga)
Release:        5.8
Codename:       Tikanga
[newcc@vm0166 CC-master]$ pwd
/ulic/newcc/tools/CC/CC-master
