### ISSUE TITLE
tools\agentbar 编译不通过

### ISSUE THREAD

**Issue by pplppo1314** [Baidu-ecom/CC#9]
运行build.bat，在编译CCAgentBar和CCAgentBarTest时报错，日志如下：

正在创建类型库...
Processing .\CCAgentBar.idl
CCAgentBar.idl
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\oaidl.idl
oaidl.idl
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objidl.idl
objidl.idl
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\unknwn.idl
unknwn.idl
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\wtypes.idl
wtypes.idl
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\basetsd.h
basetsd.h
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\guiddef.h
guiddef.h
Processing C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\oaidl.acf
oaidl.acf
正在编译...
stdafx.cpp
stdafx.cpp(0) : fatal error C1033: 无法打开程序数据库

**Comment by chenyuzhen** [comment]
已经解决
